version: '3.7'
services:

  nrt_container:
    hostname: localhost.com
    container_name: "nrt"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./:/var/www/app
    ports:
      - "80:80"
      - "443:443"
    restart: always
